### ISSUE TITLE
Splash.bin file doesn't work

### ISSUE THREAD

**Issue by malicious50** [sebascontre/bootscreen3ds#7]
I used the splash before and worked like a charm, now I updated Luma to 7.0.1 and splash.bin file doesn't want to work. Folder is /luma , settings are right (splash before payloads), but I see no splash screen at all. I am using Google Chrome 64bit browser (ver 57), with uBlock Origin activated, and I generated the splash.bin via this:
https://sebascontre.github.io/bootscreen3ds/
With these settings:
[Imgur](http://i.imgur.com/T3sBXqi.png)
But it doesn't work at all, I have had no problem before!
I tried to generate the splash.bin with Firefox 32bit too but had no luck.
SOLUTION: I managed to get it to work by downloading the .png file and then convert it to .bin using this site:
https://xem.github.io/3DShomebrew/tools/image-to-bin.html
(keep rotate 90° option checked), but I opened the issue anyway because I think there is a .bin file generation problem. If you wish to compare the files, this is the .bin file generated by your site (that didn't work for me):
https://ufile.io/oswhs
And this is the splash.bin file generated by the link above, that works for me:
https://ufile.io/0b1m5
Hope it helps to discover any issue! (if there are, maybe I am the only one that had this problem)

**Comment by qimiko** [comment]
I've looked at both of them, and it does seem like the site does have a problem with .bin conversion. However, it doesn't seem like anything was changed with the .bin generator. Your png to bin splash seems to not work on the bin to png, but I haven't tested it with my 3DS, since I use bootanim9 for the bootup. (which actually broke with the 11.3 or Luma update.)

For reference, I have the one I got from the site, your broken .bin, and the one you converted yourself, converted to PNG and .bin, plus one downloaded to PNG format.


[splash.zip](https://github.com/sebascontre/bootscreen3ds/files/945920/splash.zip)

I don't know the .bin format, so I can't really help other than by saying that it isn't just you.
